[project]
name = "langchain-space"
version = "0.1.0"
description = "A basics exploration on LangChain."
requires-python = ">=3.12"
dependencies = [
    "langchain-openai>=0.3.3",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
]
